name: equivariant_splitting
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.6.2=py312h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - bleach=6.2.0=py312h06a4308_0
  - boltons=23.0.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_0
  - conda-package-handling=2.2.0=py312h06a4308_0
  - conda-package-streaming=0.9.0=py312h06a4308_0
  - cryptography=41.0.7=py312hdda0065_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.8.0=py312h06a4308_0
  - expat=2.5.0=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_0
  - frozendict=2.4.2=py312h06a4308_0
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py312h06a4308_0
  - ipykernel=6.29.5=py312h06a4308_0
  - ipython=8.27.0=py312h06a4308_0
  - jedi=0.19.1=py312h06a4308_0
  - json5=0.9.25=py312h06a4308_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.2.5=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h6ac8c49_2
  - libcurl=8.5.0=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.3=haf1ee3a_0
  - libmambapy=1.5.3=py312h2dafd23_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.24=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.4=hf1b16e4_1
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - menuinst=2.0.2=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.16.4=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - notebook=7.2.2=py312h06a4308_1
  - notebook-shim=0.2.3=py312h06a4308_0
  - openssl=3.0.16=h5eee18b_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=23.1=py312h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - prometheus_client=0.21.0=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py312h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.1=h996f2a0_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - pytz=2024.1=py312h06a4308_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.32.3=py312h06a4308_1
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.10.6=py312h4aa5aa6_1
  - ruamel.yaml=0.17.21=py312h5eee18b_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=68.2.2=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.4.1=py312h5eee18b_0
  - traitlets=5.14.3=py312h06a4308_0
  - truststore=0.8.0=py312h06a4308_0
  - urllib3=2.1.0=py312h06a4308_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.41.2=py312h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py312h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.0
      - addict==2.4.0
      - aggdraw==1.3.19
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - albucore==0.0.20
      - albumentations==1.4.21
      - alembic==1.16.4
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrs==23.2.0
      - autograd==1.7.0
      - bitsandbytes==0.47.0
      - blinker==1.9.0
      - bm3d==4.0.1
      - bm4d==4.2.3
      - cachetools==5.5.2
      - cfgv==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - databricks-sdk==0.61.0
      - datasets==2.20.0
      - dill==0.3.8
      - distlib==0.4.0
      - dnspython==2.6.1
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - escnn==1.0.11
      - eval-type-backport==0.2.0
      - executing==2.2.1
      - facexlib==0.3.0
      - fastapi==0.116.1
      - fastmri==0.3.0
      - filelock==3.13.3
      - filterpy==1.4.5
      - fire==0.6.0
      - flask==3.1.1
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.3.1
      - future==1.0.0
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.40.3
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.3
      - grpcio==1.65.5
      - gunicorn==23.0.0
      - h5py==3.10.0
      - hdf5storage==0.1.19
      - huggingface-hub==0.22.2
      - icecream==2.1.7
      - identify==2.6.13
      - imageio==2.34.0
      - importlib-metadata==8.7.0
      - iniconfig==2.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - keras==3.5.0
      - kiwisolver==1.4.5
      - kornia==0.6.12
      - lazy-loader==0.4
      - libclang==18.1.1
      - libcpab==0.1.1
      - lie-learn==0.0.2
      - lightning-utilities==0.11.2
      - llvmlite==0.44.0
      - lmdb==1.7.3
      - mako==1.3.10
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - mlflow==2.22.0
      - mlflow-skinny==2.22.0
      - mlflow-tracing==3.2.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - munch==4.0.0
      - namex==0.0.8
      - natsort==8.4.0
      - networkx==3.3
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opentelemetry-api==1.36.0
      - opentelemetry-sdk==1.36.0
      - opentelemetry-semantic-conventions==0.57b0
      - opt-einsum==3.3.0
      - optree==0.12.1
      - pandas==2.2.1
      - pi==0.1.2
      - pillow==10.3.0
      - pre-commit==4.3.0
      - pretrainedmodels==0.7.4
      - protobuf==4.25.3
      - psutil==5.9.8
      - py3nj==0.2.1
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydicom==3.0.1
      - pygments==2.18.0
      - pyiqa==0.1.14.1
      - pymanopt==2.2.1
      - pyparsing==3.1.2
      - pytest==8.2.1
      - pytorch-ignite==0.5.1
      - pytorch-lightning==2.2.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - regex==2025.9.1
      - rich==13.7.1
      - rsa==4.9.1
      - ruff==0.12.11
      - runstats==2.0.0
      - safetensors==0.6.2
      - scikit-image==0.22.0
      - scikit-learn==1.5.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==1.44.1
      - setproctitle==1.3.3
      - simsimd==6.2.1
      - smmap==5.0.1
      - soupsieve==2.6
      - sqlalchemy==2.0.42
      - sqlparse==0.5.3
      - starlette==0.47.2
      - stringzilla==3.11.0
      - svgwrite==1.4.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.2.12
      - timm==0.9.12
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.2.2
      - torchmetrics==1.3.2
      - torchsummary==1.5.1
      - torchvision==0.17.2
      - tqdm==4.66.4
      - transformers==4.37.2
      - typing-extensions==4.14.1
      - tzdata==2024.1
      - uv==0.8.2
      - uvicorn==0.35.0
      - virtualenv==20.34.0
      - visualtorch==0.2.3
      - wandb==0.16.6
      - werkzeug==3.1.3
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.9.4
      - zipp==3.23.0
