dataset_name: "MNIST"
operation: "CS"
noise: null
oversampling_ratio: 0.3
n_images: 20000
method: "supervised"
batch_size: 25
epochs: 500
learning_rate: 0.0001
losses_name:
  - "mse"
model: "unroll_UNet_no_norm"
losses_params:
  mse:
    metric: "MSELoss"