dataset_name: "DIV2K"
operation: "inpainting"
noise: null
oversampling_ratio: 0.3
n_images: 800
method: "unsupervised"
batch_size: 10
epochs: 200
learning_rate: 0.0002
losses_name:
  - "Split"
model: "UNet_equi_no_norm"
losses_params:
  Split:
    metric: "MSELoss"
    eval_split_input: true
    eval_n_samples: 10
    split_ratio: 0.8
    full: true