acceleration: 6
center_fraction: 0.08
noise_sigma: 0.1
epochs: 1000
batch_size: 4
learning_rate: 0.0001
weight_decay: 0.00000001
scheduler: "80%/2"
loss: "r2r-ssdu"
denoiser_kind: "UNet"
denoiser_normalization: "none"
denoiser_reynolds_group: "Trivial"
reconstructor_kind: "MoDL"
reconstructor_reynolds_group: "Trivial"
