acceleration: 8
center_fraction: 0.03
noise_sigma: 0.005
epochs: 150
batch_size: 4
learning_rate: 0.0001
weight_decay: 0.00000001
scheduler: "80%/2"
loss: "sup"
denoiser_kind: "UNet"
denoiser_normalization: "none"
denoiser_reynolds_group: "Trivial"
reconstructor_kind: "MoDL"
reconstructor_reynolds_group: "Trivial"
